<?php

declare(strict_types=1);

/** @var Veldora\Framework\Http\Router $router */

$router->get('/', [App\Controllers\HomeController::class, 'index']);

// ─── Authentication Routes (generated by make:auth) ─────────────────────────
$router->get('/login',  [App\Controllers\LoginController::class, 'show'])->name('login')->middleware(['guest']);
$router->post('/login', [App\Controllers\LoginController::class, 'login'])->middleware(['guest']);
$router->post('/logout',[App\Controllers\LoginController::class, 'logout'])->name('logout')->middleware(['auth']);

$router->get('/register',  [App\Controllers\RegisterController::class, 'show'])->name('register')->middleware(['guest']);
$router->post('/register', [App\Controllers\RegisterController::class, 'register'])->middleware(['guest']);

$router->get('/forgot-password',  [App\Controllers\ForgotPasswordController::class, 'show'])->name('password.request')->middleware(['guest']);
$router->post('/forgot-password', [App\Controllers\ForgotPasswordController::class, 'send'])->name('password.email')->middleware(['guest']);

$router->get('/reset-password',   [App\Controllers\ResetPasswordController::class, 'show'])->name('password.reset')->middleware(['guest']);
$router->post('/reset-password',  [App\Controllers\ResetPasswordController::class, 'reset'])->name('password.update')->middleware(['guest']);

$router->get('/profile',           [App\Controllers\ProfileController::class, 'show'])->name('profile.show')->middleware(['auth']);
$router->put('/profile',           [App\Controllers\ProfileController::class, 'update'])->name('profile.update')->middleware(['auth']);
$router->put('/profile/password',  [App\Controllers\ProfileController::class, 'changePassword'])->name('profile.password')->middleware(['auth']);

$router->get('/email/verify',  [App\Controllers\VerificationController::class, 'notice'])->name('verification.notice')->middleware(['auth']);
$router->get('/email/verify/{id}', [App\Controllers\VerificationController::class, 'verify'])->name('verification.verify')->middleware(['auth']);
$router->post('/email/resend', [App\Controllers\VerificationController::class, 'resend'])->name('verification.resend')->middleware(['auth']);